baseline_model:
  random_seed: 255
  cat_cols: ["Store_Type", "Location_Type", "Region_Code", "Discount"]
  lookback_days: 25
  rolls: [3,5,7,10,15,20]
  lags: [1,3,5,7,10,15,20]
  pcts: [1,3,5,7,10,15]
  pct_feats: False
  roll_feats: True
  roll_fx: {"min", "mean", "max"}
  param_type: params1
  param_opt: False
  params1:
    {
     "application": "tweedie",
    'tweedie_variance_power': 1.1,
    "num_iterations": 10000,
    "learning_rate": 0.02,
    "early_stopping_round": 50,
    "feature_fraction": 0.5,
    "bagging_fraction": 0.5,
    "subsample_freq": 1,
    "metric": "l1",
    "num_leaves":  150,
     'min_split_gain': 0.1,
      'min_child_weight': 10.773962537127826,
    "verbose": -1,
    "device_type": 'cpu'
}
  params2:
    {
      "application": "fair",
      "num_iterations": 10000,
      "learning_rate": 0.02,
      "early_stopping_round": 30,
      "feature_fraction": 0.8,
      "bagging_fraction": 0.9,
      "subsample_freq": 5,
      "num_leaves": 130,
      "metric": "l1",
      "reg_alpha": 0.3899,
      "reg_lambda": 0.648,
      "verbose": -1,
      "device_type": 'cpu'
    }
  params3:
    {
      "application": "quantile",
      "num_iterations": 10000,
      "learning_rate": 0.02,
      "early_stopping_round": 30,
      "feature_fraction": 0.8,
      "bagging_fraction": 0.9,
      "subsample_freq": 5,
      "num_leaves": 130,
      "metric": "l1",
      "reg_alpha": 0.3899,
      "reg_lambda": 0.648,
      "verbose": -1,
      "device_type": 'cpu'
    }
