python competition_code/make_dataset.py
python competition_code/create_features.py
python competition_code/hyperparameter_opt.py
python competition_code/train_model.py
python competition_code/model_serving.py